default:
  image:
    name: node
    entrypoint: ['/usr/bin/env']
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
      - node_modules

stages:
  - test

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store

test:
  stage: test
  script:
    - cd app/
    - pnpm install
    - pnpm build
    - pnpm test
