default:
  image: node

stages:
  - setup
  - build
  - test
  - deploy

install:
  stage: setup
  before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store

build:
  stage: build
  script:
    - npm run build
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  environment:
    name: production
    url: https://deb1g19.netlify.app
  only:
    - master
  script:
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
