default:
  image: node
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
      - node_modules

stages:
  - install
  - test
  - deploy

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store

install:
  stage: install
  script:
    - pnpm install

test:
  stage: test
  script:
    - pnpm build
    - pnpm test

deploy:
  stage: deploy
  environment:
    name: production
    url: https://acecoder.netlify.app
  only:
    - master
  script:
    - pnpm vercel login 06berrydan@gmail.com
    - pnpm vercel
    - pnpm vercel logout
