default:
  image: node

stages:
  - test
  - build
  - deploy

lint:
  stage: test
  script:
    - yarn install --progress=false
    - yarn run format
    - yarn run lint

test:
  stage: test
  script:
    - yarn install --progress=false
    - yarn run test

build:
  stage: build
  script:
    - yarn install --progress=false
    - yarn run build

deploy-dev:
  only:
    - master
  stage: deploy
  script:
    - npx vercel
