default:
  image: node
  cache:
    key: '$CI_COMMIT_REF_SLUG'
    paths:
      - .pnpm-store
      - node_modules

stages:
  - install
  - test

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store

install:
  stage: install
  script:
    - cd app
    - pnpm install

test:
  stage: test
  script:
    - cd app
    - pnpm build
    - pnpm test
