default:
  image: node

stages:
  - build
  - test
  - deploy

lint:
  stage: test
  script:
    - yarn install
    - yarn run format
    - yarn run lint

test:
  stage: test
  script:
    - yarn install
    - yarn run test

build:
  except:
    - master
  stage: build
  script:
    - yarn install
    - yarn run build

deploy:
  stage: deploy
  environment:
    name: production
    url: https://deb1g19.netlify.app
  only:
    - master
  script:
    - yarn install
    - yarn run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
