default:
  image: node

stages: ['test', 'build', 'deploy']

install_dependencies:
  stage: .pre
  script:
    - npm install

lint:
  stage: test
  script:
    - yarn run format
    - yarn run lint

test:
  stage: test
  script:
    - yarn run test

build:
  stage: build
  script:
    - yarn run build

deploy-dev:
  stage: deploy
  script:
    - npx vercel
