default:
  image: node

stages:
  - build
  - test
  - deploy

lint:
  stage: test
  script:
    - pnpm install
    - pnpm run format
    - pnpm run lint

test:
  stage: test
  script:
    - pnpm install
    - pnpm run test

build:
  except:
    - master
  stage: build
  script:
    - pnpm install
    - pnpm run build

deploy:
  stage: deploy
  environment:
    name: production
    url: https://deb1g19.netlify.app
  only:
    - master
  script:
    - pnpm install
    - pnpm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
