default:
  image: node

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install
  script:
    - yarn run build

lint:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - yarn run format
    - yarn run lint

test:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - yarn run test

deploy:
  only:
    - master
  stage: deploy
  before_script:
    - yarn config set cache-folder .yarn
    - yarn install --frozen-lockfile
  script:
    - npx vercel
